# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://v13.baty.net/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 20
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  [permalinks.page]
    posts = '/:year/:month/:slug/'
    journal = '/journal/:year/:month/:day/:slug/'