baseURL: 'https://baty.net/'
languageCode: en-us
title: ~/Baty.net

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true



languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: About
                  url: about/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 12
                - name: Search
                  url: search/
                  weight: 13
                - name: Uses
                  url: uses/
                  weight: 14
                - name: Daily Notes
                  url: https://daily.baty.net
                  weight: 15
                - name: ✨ Hire Me
                  url: hire-me/
                  weight: 20
                

outputs:
    home:
        - HTML
        - RSS
        - JSON

permalinks:
  posts: /:year/:slug/
  journal: /journal/:year-:month-:day/

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Baty.net - A personal weblog by Jack Baty"
    author: Jack Baty
    # author: ["Me", "You"] # multiple authors

    defaultTheme: light
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    ShowWordCount: true
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    comments: true
    images: ["papermod-cover.png"]

#  assets:
#     # disableHLJS: true # to disable highlight.js
#     # disableFingerprinting: true
#     favicon: "<link / abs url>"
#     favicon16x16: "<link / abs url>"
#     favicon32x32: "<link / abs url>"
#     apple_touch_icon: "<link / abs url>"
#     safari_pinned_tab: "<link / abs url>"
#     
    # home-info mode
    homeInfoParams:
        Title: Hi, I'm Jack Baty 👋
        Content: "Director of Unspecified Services. (Psst: ✨ <a href=\"/hire-me\">Hire Me!</a>)"

    socialIcons:
      - name: "email"
        title: "Email"
        url: "mailto:jack@baty.net"
      - name: "mastodon"
        title: "Mastodon"
        url: "https://social.lol/@jbaty"
      - name: "flickr"
        title: "Flickr"
        url: "https://flickr.com/photos/jbaty"
      - name: "rss"
        title: "RSS"
        url: "/index.xml"

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
        keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod
