baseURL = "https://baty.net/"
languageCode = "en-us"
theme = "anubis2"
title = "Baty.net"

[params.author]
name = "Jack Baty"
email  = "jack@baty.net"
location = "West Michigan, USA"

[pagination]
pagerSize = 10

[services.rss]
Limit = 10

[minify]
disableXML = true

[params]
description = "A blog about everything by Jack Baty"
dateFormat = "2 Jan 2006" #"2006-01-02"
paginationSinglePost = true
images = ['/img/opengraph2.jpg']

mainSections = ["posts","journal"]
sectionsWithFullContentOnListPage = ""

colorTheme = "auto"
colorThemeSwitcher = true

customCSS = ["css/custom.css"]

readMore = true
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
math = false # true: enable mathjax globally (default is false)
toc = true


social = [
    { id = "email", url = "jack@baty.net" }
]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[[menu.main]]
name = "🔎"
identifier = "search"
url = "/search/"
weight = 5

[languages]
[languages.en]
languageName = "English"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth           = 4

[permalinks]
[permalinks.page]
posts = "/posts/:year/:month/:slug/"
journal = "/journal/:year/:month/:day/:slug"
