#+hugo_base_dir: ../
#+hugo_section: ./
#+hugo_weight: nil
#+hugo_auto_set_lastmod: t
#+hugo_front_matter_key_replace: description>summary author>nil
#+author: Jack Baty
#+options: broken-links:t d:t
#+todo: TODO(t) | DONE(d!)
#+macro: mark @@html:<mark>$1</mark>@@
#+macro: fig @@html:{{< figure src="$1" caption="$2" >}}@@
#+macro: img @@html:{{< figure src="$1" caption="$2" >}}@@
#+hugo_front_matter_format: yaml
#+setupfile: ~/org/_SETUP/HTML_FANCY
#+startup: overview

* Notes
** 2026
*** January 2026 Notes
:PROPERTIES:
:EXPORT_HUGO_SECTION: notes/2026/01
:END:

**** DONE I'm out of the Leica SL system
CLOSED: [2026-01-21 Wed 04:19]
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: 2026-01-21-i'm-out-of-the-leica-sl-system
:EXPORT_HUGO_SLUG: i'm-out-of-the-leica-sl-system
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :cover '((image . "sl2.jpg") (caption . ""))
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-01-21 Wed 04:19]
:END:

Looks like I'm out of the Leica SL system. I just sold the 70mm Macro lens and that's the last of it. I'll probably miss having a big, interchangeable-lens Leica system, but the Q2 should arrive today and that ought to help take my mind off it.

**** DONE A note via ox-hugo
CLOSED: [2026-01-20 Tue 16:47]
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: 2026-01-20-a-note-post-via-ox-hugo
:EXPORT_HUGO_SLUG: a-note-post-via-ox-hugo
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-01-20 Tue 16:47]
:END:

I am once again using [[https://ox-hugo.scripter.co/][ox-hugo]]
for posting here. It's been a minute, but I found my old config and yasnippets, so it wasn't to onerous bringing it all back. So far I'm only doing these /notes this way, but I intend to roll it into the main blog also.
* Posts
** 2026
*** January 2026 Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts/2026/01
:END:

**** DONE Blogging with org-mode and ox-hugo again :blogging:hugo:orgmode:
CLOSED: [2026-01-21 Wed 04:55]
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: 2026-01-20-blogging-with-org-mode-and-ox-hugo-again
:EXPORT_HUGO_SLUG: blogging-with-org-mode-and-ox-hugo-again
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-01-21 Wed 04:55]
:END:

#+begin_description
Using an SSG for building a blog isn't complicated enough, so I added a layer of Org mode atop mine.
#+end_description

For a few years, a few years ago, I wrote all my blog posts using one big Org mode outline and let [[https://ox-hugo.scripter.co/][ox-hugo]] generate the Markdown files for Hugo. I eventually decided it was a layer of abstraction that I didn't need, so I fell back to writing in Markdown directly.

I'm really into using Emacs again (still?), so I dusted off and updated my old ox-hugo config and here I am, typing this with Emacs in a big Org mode outline.

I have a (ya)snippet for generating the posts, like so:

#+begin_example emacs-lisp :exports code
# -*- mode: snippet -*-
# name: Hugo blog post
# key: blog
# uuid: blog
# --
,**** TODO ${1:title}
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: `(format-time-string "%Y-%m-%d")`-${1:$(replace-regexp-in-string " " "-" (downcase yas-text))}
:EXPORT_HUGO_SLUG: ${1:$(replace-regexp-in-string " " "-" (downcase yas-text))}
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :coverCaption ""
:END:

,#+begin_description

,#+end_description

$0
#+end_example

The snippet prompts for a title, then creates the appropriate properties for the post.

One nice thing about this is that once the Markdown is generated, I no longer /need/ the .org file. Writing this way is a bonus, but not a requirement.


