#+hugo_base_dir: ../
#+hugo_section: ./
#+hugo_weight: nil
#+hugo_auto_set_lastmod: t
#+hugo_front_matter_key_replace: description>summary author>nil
#+author: Jack Baty
#+options: broken-links:t d:t
#+todo: TODO(t) | DONE(d!)
#+macro: mark @@html:<mark>$1</mark>@@
#+macro: fig @@html:{{< figure src="$1" caption="$2" >}}@@
#+macro: img @@html:{{< figure src="$1" caption="$2" >}}@@
#+hugo_front_matter_format: toml
#+setupfile: ~/org/_SETUP/HTML_FANCY
#+startup: overview

* Notes
** 2026
*** January 2026 Notes
:PROPERTIES:
:EXPORT_HUGO_SECTION: notes/2026/01
:END:

**** DONE Convoluted publishing
CLOSED: [2026-01-22 Thu 06:30]
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: 2026-01-22-convoluted-publishing
:EXPORT_HUGO_SLUG: convoluted-publishing
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-01-22 Thu 06:30]
:END:

Let me get this straight. To write a blog post, I create an outline in an Org mode file and write the post, which exports to a Markdown file, which exports to an HTML file, which I upload to a server. Got it.

**** DONE A new look for /notes
CLOSED: [2026-01-21 Wed 08:30]
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: 2026-01-21-a-new-look-for-notes
:EXPORT_HUGO_SLUG: a-new-look-for-/notes
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-01-21 Wed 08:30]
:END:

I've added the [[/notes][/notes]] section back to the menu here. I also reformatted the templates for notes so that the full post content is displayed, rather than just the summary. This was more difficult than expected because the PaperMod theme was being clever. Too clever. I almost switched back to the Blowfish theme, but figured it out.


**** DONE I'm out of the Leica SL system
CLOSED: [2026-01-21 Wed 04:19]
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: 2026-01-21-i'm-out-of-the-leica-sl-system
:EXPORT_HUGO_SLUG: i'm-out-of-the-leica-sl-system
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :cover '((image . "sl2.jpg") (caption . ""))
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-01-21 Wed 04:19]
:END:

Looks like I'm out of the Leica SL system. I just sold the 70mm Macro lens and that's the last of it. I'll probably miss having a big, interchangeable-lens Leica system, but the Q2 should arrive today and that ought to help take my mind off it.

**** DONE A note via ox-hugo
CLOSED: [2026-01-20 Tue 16:47]
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: 2026-01-20-a-note-post-via-ox-hugo
:EXPORT_HUGO_SLUG: a-note-post-via-ox-hugo
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-01-20 Tue 16:47]
:END:

I am once again using [[https://ox-hugo.scripter.co/][ox-hugo]]
for posting here. It's been a minute, but I found my old config and yasnippets, so it wasn't to onerous bringing it all back. So far I'm only doing these /notes this way, but I intend to roll it into the main blog also.
* Journals
** 2026
*** January 2026 Journals
:PROPERTIES:
:EXPORT_HUGO_SECTION: journal/2026/01-January
:END:
**** TODO Thursday, January 22, 2026
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: 20260122
:EXPORT_HUGO_SLUG: 22jan26
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :cover '((image . "") (caption . ""))
:END:

#+begin_description
My pens all skip. Convoluted publishing workflow.
#+end_description

#+begin_export html
<div class="compact">

- **STATUS**: Prepping for sub-zero temperatures
- **PLANS**: Avioding sub-zero temperatures
- **READING**: "The Writer's Friend" by Martin L. Gibson
- **LISTENING**: "Valentine" by Courtney Marie Andrews

</div>
#+end_export
-----

I swear every one of my gel and ballpoint pens has started skipping at once.

-----

Let me get this straight. To write a blog post, I create an outline in an Org mode file and write the post, which exports to a Markdown file, which exports to an HTML file. Got it.

-----


**** DONE Wednesday, January 21, 2026w
CLOSED: [2026-01-21 Wed 05:56]
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: 20260121
:EXPORT_HUGO_SLUG: 21jan26
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :cover '((image . "alice-lap.jpg") (caption . ""))
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-01-21 Wed 05:56]
:END:

#+begin_description
ox-hugo for journal posts, too? Well this is unnecessary.
#+end_description

#+begin_export html
<div class="compact">

- **STATUS**: Futzing with things I said I wouldn't futz with
- **PLANS**: Not leave the house
- **READING**: "Anima Rising" by Christopher Moore
- **LISTENING**: Mozart piano concertos

</div>
#+end_export

-----

The plan was to only generate [[/notes][/notes]] with ox-hugo, but I just spent like an hour getting the snippet and properties configured so I can generate these journal posts also. WHY!?

-----




* Posts
** 2026
*** January 2026 Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts/2026/01
:END:

**** DONE Blogging with org-mode and ox-hugo again :blogging:hugo:orgmode:
CLOSED: [2026-01-21 Wed 04:55]
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: 2026-01-20-blogging-with-org-mode-and-ox-hugo-again
:EXPORT_HUGO_SLUG: blogging-with-org-mode-and-ox-hugo-again
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-01-21 Wed 04:55]
:END:

#+begin_description
Using an SSG for building a blog isn't complicated enough, so I added a layer of Org mode atop mine.
#+end_description

For a few years (a few years ago) I wrote all my blog posts using one big Org mode outline and let [[https://ox-hugo.scripter.co/][ox-hugo]] generate the Markdown files for Hugo. I eventually decided it was a layer of abstraction that I didn't need, so I fell back to writing in Markdown directly.

I'm really into using Emacs for everything again (still?), so I dusted off and updated my old ox-hugo config and here I am, typing this with Emacs in a big Org mode outline.

I have a (ya)snippet for generating the posts, like so:

#+begin_example emacs-lisp :exports code
# -*- mode: snippet -*-
# name: Hugo blog post
# key: blog
# uuid: blog
# --
,**** TODO ${1:title}
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:EXPORT_HUGO_BUNDLE: `(format-time-string "%Y-%m-%d")`-${1:$(replace-regexp-in-string " " "-" (downcase yas-text))}
:EXPORT_HUGO_SLUG: ${1:$(replace-regexp-in-string " " "-" (downcase yas-text))}
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :coverCaption ""
:END:

,#+begin_description

,#+end_description

$0
#+end_example

The snippet prompts for a title, then creates the appropriate properties for the post.

One nice thing about this is that once the Markdown is generated, I no longer /need/ the .org file. Writing this way is a bonus, but not a requirement.


