languageCode = "en"
languageName = "English"
weight = 1

title = "~/Baty.net"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false

  dateFormat = "January 2, 2006"

  # mainSections = ["section1", "section2"]
  description = "A personal weblog by Jack Baty"

[author]
  name = "Jack Baty"
  image = "img/jack.jpg"
  headline = "Director of Unspecified Services"
  # bio = "A little bit about you"
  links = [
    { email = "mailto:jack@baty.net" },
    # { link = "https://link-to-some-website.com/" },
    { flickr = "https://www.flickr.com/photos/jbaty/" },
    { mastodon = "https://social.lol/@jbaty" },
 ]

